[component]
structures = [ "content_blocks" ]
label = "Hero"
description = "Page hero with the heading, description, buttons, and an image"
icon = "wysiwyg"
tags = ["Structure", "Text", "Links"]

[props]
title = "Hi there, I'm Sean Davis"
description_html = "<p><strong>Software Developer</strong> from Louisville, KY. I build high-performance and user-centric experiences for web, mobile, and the Linux desktop.</p>"
image = "/images/sean-davis-headshot.jpg"
image_alt = "Sean Davis's picture"
cta_button = "Get the latest updates"
cta_button_link = "https://blog.bluesabre.org"
works_button = "See my projects"
works_button_link = "#projects"