[component]
structures = [ "content_blocks" ]
label = "Project Summary"
description = "Page hero with project features and video"
icon = "wysiwyg"
tags = ["Structure", "Text", "Links"]

[props]
title = ""
description = ""
description_html = "<p></p>"
features = ""
featured_video = ""