[component]
structures = [ "content_blocks" ]
label = "Contact Form"
description = "Generic contact form"
icon = "wysiwyg"
tags = ["Text"]

[props]
form_title = "Get in touch"
form_description = "Send me a message. Powered by Formspree."
form_submission_url = ""
form_button_text = "Send now"