title: 'Sean Davis'

plugins:
  - jekyll-bookshop
  - cloudcannon-jekyll-bookshop
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-last-modified-at

# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ../components

exclude:
  - postcss.config.js
  - node_modules

include:
  - _cloudcannon

# The rest of this array structure will be
# populated by the bookshop-array-structures plugin.
_array_structures:
  content_blocks:
    style: modal

collections_dir: 'collections'

collections:
  pages:
    output: true
    permalink: /:title/
  projects:
    output: true
    permalink: /projects/:slug

cloudcannon:
  collections:
    pages:
      _icon: 'wysiwyg'
    projects:
      _icon: 'work_outline'
      _subtext_key: subtitle

_collection_groups:
  - heading: Content
    collections:
      - pages
      - projects
  - heading: Blogging
    collections:
      - drafts
  - heading: Settings
    collections:
      - data

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
      path: _pages/index.html
    values:
      permalink: /
  - scope:
      type: projects
    values:
      layout: project
