title: 'Sean Davis'
description: >-
  Xfce, Xubuntu, and elementary contributor. Free your PC with free and open-source software.
social_media_share_image: /images/pages/home/home-shared.png
disqus-identifier:
google-analytics: G-GWYZHQEQ87