[component]
structures = [ "content_blocks" ]
label = "Project Featured In"
description = "Standout featured-in section"
icon = "wysiwyg"
tags = ["Structure", "Text", "Links"]

[props]
featured_in = "Xubuntu"
description_html = "<p>Since 2023</p>"
image = "/images/projects/xubuntu-128.png"
image_alt = "Xubuntu logo"