[component]
structures = [ "content_blocks" ]
label = "Left Right Content"
description = "Left/right split content areas"
icon = "wysiwyg"
tags = ["Structure", "Text", "Links"]

[props]
left_content = "<p></p>"
right_content = "<p></p>"