[component]
structures = [ "content_blocks" ]
label = "Project Whats New"
description = "Feature section to link to recent updates"
icon = "wysiwyg"
tags = ["Structure", "Text", "Links"]

[props]
title = ""
url = ""
domain = ""