name: Build & Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Jekyll
        env:
          BUNDLE_GEMFILE: site/Gemfile 
        run: |
          sudo gem install bundler jekyll
          sudo bundle install

      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
        env:
          JEKYLL_ENV: production